import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:form_builder_validators/form_builder_validators.dart';

import '../../data/models/grocery_item_model.dart';
import '../providers/grocery_list_provider.dart';

class AddGroceryItemScreen extends ConsumerStatefulWidget {
  const AddGroceryItemScreen({super.key, this.item});

  final GroceryItemModel? item;

  @override
  ConsumerState<AddGroceryItemScreen> createState() => _AddGroceryItemScreenState();
}

class _AddGroceryItemScreenState extends ConsumerState<AddGroceryItemScreen> {
  final _formKey = GlobalKey<FormBuilderState>();
  bool _isSubmitting = false;

  static const List<String> _categories = <String>[
    'Produce',
    'Dairy',
    'Meat',
    'Bakery',
    'Pantry',
    'Snacks',
    'Frozen',
    'Beverages',
    'Household',
    'Other',
  ];

  @override
  Widget build(BuildContext context) {
    final isEdit = widget.item != null;

    return Scaffold(
      appBar: AppBar(
        title: Text(isEdit ? 'Edit Grocery Item' : 'Add Grocery Item'),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: FormBuilder(
            key: _formKey,
            autovalidateMode: AutovalidateMode.onUserInteraction,
            initialValue: <String, dynamic>{
              'name': widget.item?.name ?? '',
              'quantity': widget.item?.quantity.toString() ?? '1',
              'category': widget.item?.category ?? _categories.first,
              'autoGenerated': widget.item?.isAutoGenerated ?? false,
            },
            child: Column(
              children: [
                FormBuilderTextField(
                  name: 'name',
                  decoration: const InputDecoration(
                    labelText: 'Name',
                    prefixIcon: Icon(Icons.edit),
                  ),
                  textCapitalization: TextCapitalization.words,
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(),
                    FormBuilderValidators.minLength(2),
                  ]),
                ),
                const SizedBox(height: 16),
                FormBuilderTextField(
                  name: 'quantity',
                  decoration: const InputDecoration(
                    labelText: 'Quantity',
                    prefixIcon: Icon(Icons.numbers),
                  ),
                  keyboardType: TextInputType.number,
                  validator: FormBuilderValidators.compose([
                    FormBuilderValidators.required(),
                    FormBuilderValidators.integer(),
                    FormBuilderValidators.min(1),
                  ]),
                ),
                const SizedBox(height: 16),
                FormBuilderDropdown<String>(
                  name: 'category',
                  decoration: const InputDecoration(
                    labelText: 'Category',
                    prefixIcon: Icon(Icons.category),
                  ),
                  items: _categories
                      .map((category) => DropdownMenuItem<String>(
                            value: category,
                            child: Text(category),
                          ))
                      .toList(),
                  validator: FormBuilderValidators.required(),
                ),
                const SizedBox(height: 16),
                if (widget.item?.isAutoGenerated ?? false)
                  FormBuilderSwitch(
                    name: 'autoGenerated',
                    title: const Text('Mark as auto-generated'),
                    decoration: const InputDecoration(border: InputBorder.none),
                  ),
                const Spacer(),
                SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: _isSubmitting ? null : _submit,
                    child: _isSubmitting
                        ? const SizedBox(
                            height: 20,
                            width: 20,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : Text(isEdit ? 'Save Changes' : 'Add Item'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Future<void> _submit() async {
    if (!(_formKey.currentState?.saveAndValidate() ?? false)) {
      return;
    }

    setState(() => _isSubmitting = true);

    final values = _formKey.currentState!.value;
    final controller = ref.read(groceryListControllerProvider.notifier);
    final now = DateTime.now();

    final item = GroceryItemModel(
      id: widget.item?.id ?? DateTime.now().millisecondsSinceEpoch.toString(),
      name: values['name'] as String,
      quantity: int.parse(values['quantity'] as String),
      category: values['category'] as String,
      isChecked: widget.item?.isChecked ?? false,
      isAutoGenerated: values['autoGenerated'] as bool? ?? false,
      pantryItemId: widget.item?.pantryItemId,
      createdAt: widget.item?.createdAt ?? now,
      updatedAt: now,
    );

    try {
      if (widget.item == null) {
        await controller.addItem(item);
      } else {
        await controller.updateItem(item);
      }
      if (!mounted) return;
      Navigator.pop(context);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(widget.item == null ? 'Item added' : 'Item updated')),
      );
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }
}
