// lib/features/grocery_list/data/models/grocery_item_model.dart

import 'package:hive/hive.dart';

part 'grocery_item_model.g.dart';

@HiveType(typeId: 2)
class GroceryItemModel extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final int quantity;

  @HiveField(3)
  final String category;

  @HiveField(4)
  final bool isChecked;

  @HiveField(5)
  final bool isAutoGenerated;

  @HiveField(6)
  final String? pantryItemId; // Reference to pantry item if auto-generated

  @HiveField(7)
  final DateTime createdAt;

  @HiveField(8)
  final DateTime updatedAt;

  GroceryItemModel({
    required this.id,
    required this.name,
    required this.quantity,
    required this.category,
    this.isChecked = false,
    this.isAutoGenerated = false,
    this.pantryItemId,
    required this.createdAt,
    required this.updatedAt,
  });

  GroceryItemModel copyWith({
    String? id,
    String? name,
    int? quantity,
    String? category,
    bool? isChecked,
    bool? isAutoGenerated,
    String? pantryItemId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return GroceryItemModel(
      id: id ?? this.id,
      name: name ?? this.name,
      quantity: quantity ?? this.quantity,
      category: category ?? this.category,
      isChecked: isChecked ?? this.isChecked,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      pantryItemId: pantryItemId ?? this.pantryItemId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is GroceryItemModel &&
        other.id == id &&
        other.name == name &&
        other.quantity == quantity &&
        other.category == category &&
        other.isChecked == isChecked &&
        other.isAutoGenerated == isAutoGenerated &&
        other.pantryItemId == pantryItemId &&
        other.createdAt == createdAt &&
        other.updatedAt == updatedAt;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        name.hashCode ^
        quantity.hashCode ^
        category.hashCode ^
        isChecked.hashCode ^
        isAutoGenerated.hashCode ^
        pantryItemId.hashCode ^
        createdAt.hashCode ^
        updatedAt.hashCode;
  }
}