// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'grocery_item_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class GroceryItemModelAdapter extends TypeAdapter<GroceryItemModel> {
  @override
  final int typeId = 2;

  @override
  GroceryItemModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return GroceryItemModel(
      id: fields[0] as String,
      name: fields[1] as String,
      quantity: fields[2] as int,
      category: fields[3] as String,
      isChecked: fields[4] as bool,
      isAutoGenerated: fields[5] as bool,
      pantryItemId: fields[6] as String?,
      createdAt: fields[7] as DateTime,
      updatedAt: fields[8] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, GroceryItemModel obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.quantity)
      ..writeByte(3)
      ..write(obj.category)
      ..writeByte(4)
      ..write(obj.isChecked)
      ..writeByte(5)
      ..write(obj.isAutoGenerated)
      ..writeByte(6)
      ..write(obj.pantryItemId)
      ..writeByte(7)
      ..write(obj.createdAt)
      ..writeByte(8)
      ..write(obj.updatedAt);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroceryItemModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
